version: 2.1

jobs:
  build_and_train:
    docker:
      # Specify the Docker image to use. Adjust the Python version as needed.
      - image: cimg/python:3.8
      
    working_directory: ~/repo

    steps:
      - checkout

      # Restore the cached dependencies, if any
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      # Save the dependencies for caching, to speed up future builds
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
          
      # Prepare the EEG dataset
      - run:
          name: Prepare EEG Dataset
          command: python prepare_dataset.py

      # Train the machine learning model
      - run:
          name: Train Model
          command: python train_model.py

# Define workflows
workflows:
  version: 2
  build_and_train_workflow:
    jobs:
      - build_and_train
