version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8  # Using CircleCI's Python image. Adjust the version as necessary.
    working_directory: ~/repo
    steps:
      - checkout  # Check out your code
      - run:
          name: Set up Python environment
          command: |
            python -m venv venv
            echo "source venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            pip install torch numpy  # Add any other dependencies you might have
      - run:
          name: Prepare data and train model
          command: |
            # Assuming your script and data are in the root. Adjust paths as necessary.
            python train_model.py
      - run:
          name: Save model to Workspace
          command: |
            # This step assumes your model is saved in the root as 'SavedModel.pth'.
            # Adjust the path as necessary.
            mkdir -p /tmp/workspace/
            cp /content/drive/MyDrive/SavedModel.pth /tmp/workspace/
      - persist_to_workspace:
          root: /tmp/workspace/
          paths:
            - SavedModel.pth

workflows:
  version: 2
  build_and_train:
    jobs:
      - build
